## numpy - Numerical Python Library

In [1]:
import numpy as np

In [5]:
a = np.array([3,4,5,6,7])

In [6]:
type(a)

numpy.ndarray

In [7]:
a1 = np.array([[3,4,5], [2,3,4]])

In [8]:
a1

array([[3, 4, 5],
       [2, 3, 4]])

In [9]:
a1.shape

(2, 3)

In [10]:
a1.ndim

2

In [11]:
a1.size

6

In [12]:
# generate random data
np.random.randint(1,10)

3

In [13]:
# generate random data with different shape
np.random.randint(1,10,(3,3))

array([[9, 5, 6],
       [6, 7, 7],
       [9, 3, 5]])

In [14]:
np.random.randint(1,10,(2,4,3)) # 2 sets of 4X3 data

array([[[9, 7, 9],
        [2, 9, 3],
        [1, 3, 9],
        [1, 9, 3]],

       [[3, 2, 9],
        [1, 8, 2],
        [5, 9, 7],
        [4, 2, 2]]])

## Transform Image into Numpy array

In [15]:
from PIL import Image

img = Image.open('pexels-mikebirdy-3729464.jpg')

In [16]:
car_array = np.array(img)
car_array

array([[[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 63,  84,  17],
        [ 64,  85,  18],
        [ 64,  85,  18]],

       [[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 63,  84,  17],
        [ 64,  85,  18],
        [ 64,  85,  18]],

       [[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 64,  85,  18],
        [ 65,  86,  17],
        [ 65,  86,  17]],

       ...,

       [[139, 131, 118],
        [141, 133, 120],
        [143, 135, 122],
        ...,
        [147, 147, 135],
        [148, 148, 136],
        [149, 149, 137]],

       [[135, 127, 114],
        [137, 129, 116],
        [139, 131, 118],
        ...,
        [148, 148, 136],
        [149, 149, 137],
        [150, 150, 138]],

       [[132, 124, 111],
        [134, 126, 113],
        [137, 129, 116],
        ...,
        [149, 149, 137],
        [150, 150, 138],
        [151, 151, 139]]

In [17]:
car_array.ndim

3

In [18]:
car_array.size

59448576

In [19]:
car_array.shape

(3632, 5456, 3)

In [20]:
# To validate open the file
#Image.open('info-pexels-mikebirdy-3729464.png')

## Index wise operations for numpy arrays

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [25]:
a1 = np.array([3,4,5,6,7,7])
a2 = np.array([5,6,4,3,2,3])

In [26]:
a1+a2

array([ 8, 10,  9,  9,  9, 10])

In [27]:
a1*a2

array([15, 24, 20, 18, 14, 21])

In [28]:
a1/a2

array([0.6       , 0.66666667, 1.25      , 2.        , 3.5       ,
       2.33333333])

In [29]:
a3 = np.array([[3,4,5], [1,2,3]])
a4 = np.array([[2,3,4], [1,2,3]])

In [30]:
a3+a4

array([[5, 7, 9],
       [2, 4, 6]])

In [31]:
a3*a4

array([[ 6, 12, 20],
       [ 1,  4,  9]])

In [32]:
a3

array([[3, 4, 5],
       [1, 2, 3]])

In [33]:
a4

array([[2, 3, 4],
       [1, 2, 3]])

In [34]:
a3.ndim

2

In [35]:
a3.shape

(2, 3)

In [10]:
a1 = np.array([[2,3],[1,2]])
a2 = np.array([[1,2],[2,3]])

In [37]:
a1

array([[2, 3],
       [1, 2]])

In [38]:
a2

array([[1, 2],
       [2, 3]])

In [39]:
# NOTE: This is not Matrix Multiplication
a1*a2

array([[2, 6],
       [2, 6]])

## Matrix Multiplication - @ or np.dot

In [40]:
a1@a2

array([[ 8, 13],
       [ 5,  8]])

In [41]:
np.dot(a1,a2)

array([[ 8, 13],
       [ 5,  8]])

In [42]:
# to validate print img for car image
#img

In [43]:
car_array

array([[[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 63,  84,  17],
        [ 64,  85,  18],
        [ 64,  85,  18]],

       [[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 63,  84,  17],
        [ 64,  85,  18],
        [ 64,  85,  18]],

       [[226, 237, 239],
        [226, 237, 239],
        [226, 237, 239],
        ...,
        [ 64,  85,  18],
        [ 65,  86,  17],
        [ 65,  86,  17]],

       ...,

       [[139, 131, 118],
        [141, 133, 120],
        [143, 135, 122],
        ...,
        [147, 147, 135],
        [148, 148, 136],
        [149, 149, 137]],

       [[135, 127, 114],
        [137, 129, 116],
        [139, 131, 118],
        ...,
        [148, 148, 136],
        [149, 149, 137],
        [150, 150, 138]],

       [[132, 124, 111],
        [134, 126, 113],
        [137, 129, 116],
        ...,
        [149, 149, 137],
        [150, 150, 138],
        [151, 151, 139]]

In [44]:
car_array.size

59448576

In [45]:
car_array.shape

(3632, 5456, 3)

In [46]:
additional_data = np.random.randint(0,2, (3632, 5456, 3))

In [47]:
additional_data.shape

(3632, 5456, 3)

In [48]:
after_multi = car_array * additional_data
after_norm = (after_multi*255).astype(np.uint8) # normalize the dataset in the range of (0,255) RGB for colours

In [49]:
#after_multi
after_norm

array([[[ 30,   0,   0],
        [  0,   0,  17],
        [  0,   0,   0],
        ...,
        [193,   0,   0],
        [  0,   0,   0],
        [192,   0, 238]],

       [[ 30,   0,   0],
        [  0,   0,  17],
        [  0,   0,  17],
        ...,
        [193,   0, 239],
        [192, 171,   0],
        [  0, 171, 238]],

       [[  0,   0,   0],
        [  0,   0,  17],
        [ 30,   0,   0],
        ...,
        [  0,   0,   0],
        [  0, 170,   0],
        [  0,   0, 239]],

       ...,

       [[  0, 125, 138],
        [115,   0,   0],
        [  0, 121,   0],
        ...,
        [109,   0,   0],
        [108,   0, 120],
        [  0,   0,   0]],

       [[  0, 129, 142],
        [  0,   0,   0],
        [117, 125,   0],
        ...,
        [  0, 108, 120],
        [  0,   0,   0],
        [106, 106, 118]],

       [[  0,   0,   0],
        [  0, 130, 143],
        [119,   0, 140],
        ...,
        [  0, 107, 119],
        [106, 106,   0],
        [105,   0,   0]]

In [50]:
final_image = Image.fromarray(after_norm)

In [51]:
#final_image

In [2]:
a = np.array([3,4,5,6,7,8,9])

In [3]:
a.mean()

np.float64(6.0)

In [4]:
a.std()

np.float64(2.0)

In [5]:
a.min()

np.int64(3)

In [6]:
a.var()

np.float64(4.0)

In [7]:
np.log10(a)

array([0.47712125, 0.60205999, 0.69897   , 0.77815125, 0.84509804,
       0.90308999, 0.95424251])

In [8]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843, 2980.95798704, 8103.08392758])

In [11]:
a1

array([[2, 3],
       [1, 2]])

In [ ]:
np.linalg.inv(a1)   # inverse of a matrix

array([[ 2., -3.],
       [-1.,  2.]])